name: Studio-Pierce
favicon: null
layout_spectrum: 0.7050490682013333
typography_spectrum: 0.23585040378384292
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d4c4a'
    - '#000000'
    - '#787878'
    - '#ecebe6'
    - '#a5a49f'
  brandStrength: 0.375
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
